/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new financial account
         * @description Provisions a new account with zero balance. Supports idempotency via correlationId.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve account transaction history
         * @description Returns chronological list of movements with calculated running balance.
         */
        get: operations["getAccountHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change account operational status
         * @description Performs state transition (FREEZE/ACTIVATE) on the target account.
         */
        patch: operations["changeAccountStatus"];
        trace?: never;
    };
    "/api/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a transfer between accounts
         * @description Executes a double-entry bookkeeping transfer between source and target accounts.
         */
        post: operations["executeTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deposit cash into an account
         * @description Direct cash-in operation credited to the target account.
         */
        post: operations["depositCash"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new wallet
         * @description Creates a new virtual wallet for a user.
         */
        post: operations["createWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get wallet details
         * @description Returns wallet information by ID.
         */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get wallet balance
         * @description Returns current balance for a wallet (with Redis cache).
         */
        get: operations["getWalletBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Top up wallet with card
         * @description Processes a card-based top-up synchronously.
         */
        post: operations["cardTopUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/topup/cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate cash top-up
         * @description Creates a cash top-up with reference code. User must pay within 24 hours.
         */
        post: operations["initiateCashTopUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topups/{topUpId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm cash top-up
         * @description Confirms a cash top-up after payment at a cash point.
         */
        post: operations["confirmCashTopUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pse/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PSE payment webhook callback
         * @description Receives webhook from PSE payment gateway with HMAC validation.
         */
        post: operations["pseWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qr/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a QR code
         * @description Creates a new QR code for payment collection.
         */
        post: operations["generateQr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qr/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay a QR code
         * @description Executes a payment against a QR code. Single-use.
         */
        post: operations["payQr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay a bill
         * @description Pays a bill to a registered biller.
         */
        post: operations["payBill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get favorite billers
         * @description Returns all active billers.
         */
        get: operations["getFavoriteBillers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user notifications (inbox)
         * @description Returns all notifications for the authenticated user.
         */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Mark notification as read
         * @description Marks a specific notification as read.
         */
        put: operations["markNotificationRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kyc/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit KYC documents
         * @description Submits KYC verification documents for a user.
         */
        post: operations["submitKyc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kyc/{userId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve KYC
         * @description Approves KYC for a user and auto-creates wallet.
         */
        post: operations["approveKyc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Registers a new user with encrypted PII.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WebAccountRequest: {
            accountNumber: string;
            /** @example COP */
            currency: string;
            correlationId?: string;
            requestSource?: string;
        };
        CreateAccountResponse: {
            /** Format: uuid */
            account_id?: string;
            account_number?: string;
            currency?: string;
            balance?: string;
            correlation_id?: string;
        };
        AccountStatementResponse: {
            /** Format: uuid */
            transaction_id?: string;
            type?: string;
            amount?: string;
            balance_after?: string;
            /** Format: date-time */
            booked_at?: string;
        };
        TransferRequest: {
            /** Format: uuid */
            sourceAccountId: string;
            /** Format: uuid */
            targetAccountId: string;
            amount: string;
            currency: string;
            description?: string;
            correlationId?: string;
        };
        DepositRequest: {
            /** Format: uuid */
            targetAccountId: string;
            amount: string;
            currency: string;
            description?: string;
            correlationId?: string;
        };
        TransactionResponse: {
            /** Format: uuid */
            transaction_id?: string;
            correlation_id?: string;
            type?: string;
            status?: string;
            /** Format: date-time */
            booked_at?: string;
            amount?: string;
            currency?: string;
            description?: string;
            source_new_balance?: string;
            target_new_balance?: string;
        };
        CreateWalletRequest: {
            /** Format: uuid */
            userId: string;
            name: string;
            currency: string;
        };
        WalletResponse: {
            /** Format: uuid */
            wallet_id?: string;
            /** Format: uuid */
            user_id?: string;
            name?: string;
            currency?: string;
            status?: string;
        };
        BalanceResponse: {
            /** Format: uuid */
            wallet_id?: string;
            balance?: string;
            currency?: string;
        };
        WebCardTopUpRequest: {
            amount: string;
            currency: string;
            cardToken: string;
            correlationId?: string;
        };
        WebCashTopUpRequest: {
            amount: string;
            currency: string;
            correlationId?: string;
        };
        TopUpResponse: {
            /** Format: uuid */
            top_up_id?: string;
            /** Format: uuid */
            wallet_id?: string;
            amount?: string;
            currency?: string;
            status?: string;
            reference_code?: string;
            /** Format: date-time */
            created_at?: string;
        };
        PseWebhookRequest: {
            externalReference: string;
            success: boolean;
            amount?: string;
        };
        WebGenerateQrRequest: {
            /** Format: uuid */
            walletId: string;
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            type: "FIXED" | "DYNAMIC";
            amount?: string;
            currency: string;
            description?: string;
            ttlSeconds: number;
        };
        GenerateQrResponse: {
            /** Format: uuid */
            qrCodeId?: string;
            type?: string;
            amount?: string;
            currency?: string;
            description?: string;
            hmacPayload?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            qrImageBase64?: string;
        };
        WebPayQrRequest: {
            /** Format: uuid */
            qrCodeId: string;
            /** Format: uuid */
            payerWalletId: string;
            /** Format: uuid */
            payerUserId: string;
            amount?: string;
            hmacPayload: string;
        };
        PayQrResponse: {
            /** Format: uuid */
            paymentId?: string;
            status?: string;
            /** Format: uuid */
            transactionId?: string;
        };
        WebPayBillRequest: {
            /** Format: uuid */
            walletId: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            billerId: string;
            amount: string;
            currency: string;
            reference: string;
            correlationId?: string;
        };
        BillPaymentResponse: {
            /** Format: uuid */
            payment_id?: string;
            /** Format: uuid */
            wallet_id?: string;
            /** Format: uuid */
            biller_id?: string;
            amount?: string;
            currency?: string;
            reference?: string;
            status?: string;
            providerResponse?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Biller: {
            /** Format: uuid */
            id?: string;
            name?: string;
            category?: string;
            accountNumber?: string;
            active?: boolean;
        };
        NotificationResponse: {
            /** Format: uuid */
            notification_id?: string;
            /** Format: uuid */
            user_id?: string;
            /** @enum {string} */
            type?: "TOPUP_COMPLETED" | "P2P_RECEIVED" | "BILL_PAID" | "SECURITY_ALERT";
            title?: string;
            message?: string;
            is_read?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        WebKycSubmitRequest: {
            /** Format: uuid */
            userId: string;
            documentType: string;
            documentNumber: string;
        };
        WebRegisterRequest: {
            /** Format: email */
            email: string;
            phoneNumber: string;
            firstName: string;
            lastName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAccountRequest"];
            };
        };
        responses: {
            /** @description Account created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAccountResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account number already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAccountHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountStatementResponse"][];
                };
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeAccountStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action?: "FREEZE" | "ACTIVATE";
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Status updated successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    executeTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Transfer completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient funds */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    depositCash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositRequest"];
            };
        };
        responses: {
            /** @description Deposit completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWalletRequest"];
            };
        };
        responses: {
            /** @description Wallet created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWalletBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cardTopUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebCardTopUpRequest"];
            };
        };
        responses: {
            /** @description Top-up completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopUpResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payment declined */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    initiateCashTopUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebCashTopUpRequest"];
            };
        };
        responses: {
            /** @description Cash top-up initiated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopUpResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmCashTopUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topUpId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cash top-up confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopUpResponse"];
                };
            };
            /** @description Top-up not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Top-up expired or already processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pseWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PseWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid webhook data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid HMAC signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generateQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebGenerateQrRequest"];
            };
        };
        responses: {
            /** @description QR code generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateQrResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebPayQrRequest"];
            };
        };
        responses: {
            /** @description Payment successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayQrResponse"];
                };
            };
            /** @description Invalid or expired QR code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description QR code already used */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payBill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebPayBillRequest"];
            };
        };
        responses: {
            /** @description Bill payment completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillPaymentResponse"];
                };
            };
            /** @description Invalid input or biller not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient funds */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFavoriteBillers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active billers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Biller"][];
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"][];
                };
            };
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Notification not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitKyc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebKycSubmitRequest"];
            };
        };
        responses: {
            /** @description KYC submitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveKyc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KYC approved, wallet created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebRegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email or phone already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
